const fs = require('fs')

const list1 = [
  // ==================== BOLLYWOOD ====================
  { mainWord: "Shah Rukh Khan", imposterWord: "Salman Khan", category: "Bollywood" },
  { mainWord: "Aamir Khan", imposterWord: "Akshay Kumar", category: "Bollywood" },
  { mainWord: "Ranbir Kapoor", imposterWord: "Ranveer Singh", category: "Bollywood" },
  { mainWord: "Varun Dhawan", imposterWord: "Sidharth Malhotra", category: "Bollywood" },
  { mainWord: "Vicky Kaushal", imposterWord: "Rajkummar Rao", category: "Bollywood" },
  { mainWord: "Kartik Aaryan", imposterWord: "Ayushmann Khurrana", category: "Bollywood" },
  { mainWord: "Alia Bhatt", imposterWord: "Deepika Padukone", category: "Bollywood" },
  { mainWord: "Kareena Kapoor", imposterWord: "Priyanka Chopra", category: "Bollywood" },
  { mainWord: "Katrina Kaif", imposterWord: "Anushka Sharma", category: "Bollywood" },
  { mainWord: "Kiara Advani", imposterWord: "Shraddha Kapoor", category: "Bollywood" },
  { mainWord: "Rajinikanth", imposterWord: "Amitabh Bachchan", category: "Indian Cinema" },
  { mainWord: "Allu Arjun", imposterWord: "Ram Charan", category: "Indian Cinema" },
  { mainWord: "Prabhas", imposterWord: "Yash", category: "Indian Cinema" },
  { mainWord: "Dhanush", imposterWord: "Vijay", category: "Indian Cinema" },

  // ==================== BOLLYWOOD MOVIES ====================
  { mainWord: "3 Idiots", imposterWord: "Chhichhore", category: "Movies" },
  { mainWord: "YJHD", imposterWord: "Wake Up Sid", category: "Movies" },
  { mainWord: "Zindagi Na Milegi Dobara", imposterWord: "Dil Chahta Hai", category: "Movies" },
  { mainWord: "Jab We Met", imposterWord: "Tamasha", category: "Movies" },
  { mainWord: "Rockstar", imposterWord: "Ae Dil Hai Mushkil", category: "Movies" },
  { mainWord: "Jawan", imposterWord: "Pathaan", category: "Movies" },
  { mainWord: "Dunki", imposterWord: "Jawan", category: "Movies" },
  { mainWord: "Kabir Singh", imposterWord: "Animal", category: "Movies" },
  { mainWord: "Animal", imposterWord: "Kabir Singh", category: "Movies" },
  { mainWord: "Gully Boy", imposterWord: "Rockstar", category: "Movies" },
  { mainWord: "Bhool Bhulaiyaa", imposterWord: "Stree", category: "Movies" },
  { mainWord: "Stree", imposterWord: "Bhediya", category: "Movies" },
  { mainWord: "Welcome", imposterWord: "Hera Pheri", category: "Comedy Movies" },
  { mainWord: "Hera Pheri", imposterWord: "Phir Hera Pheri", category: "Comedy Movies" },
  { mainWord: "Dhamaal", imposterWord: "Golmaal", category: "Comedy Movies" },
  { mainWord: "Golmaal", imposterWord: "All The Best", category: "Comedy Movies" },
  { mainWord: "Krrish", imposterWord: "Ra.One", category: "Superhero Movies" },
  { mainWord: "Dhoom", imposterWord: "War", category: "Action Movies" },
  { mainWord: "Drishyam", imposterWord: "Andhadhun", category: "Thriller Movies" },
  { mainWord: "12th Fail", imposterWord: "3 Idiots", category: "Student Movies" },
  { mainWord: "Taare Zameen Par", imposterWord: "Chhichhore", category: "Student Movies" },

  // ==================== SONGS / SINGERS ====================
  { mainWord: "Arijit Singh", imposterWord: "Atif Aslam", category: "Music" },
  { mainWord: "AP Dhillon", imposterWord: "Karan Aujla", category: "Music" },
  { mainWord: "Diljit Dosanjh", imposterWord: "Badshah", category: "Music" },
  { mainWord: "Anuv Jain", imposterWord: "Prateek Kuhad", category: "Music" },
  { mainWord: "Shreya Ghoshal", imposterWord: "Sunidhi Chauhan", category: "Music" },
  { mainWord: "Jubin Nautiyal", imposterWord: "Darshan Raval", category: "Music" },
  { mainWord: "King", imposterWord: "MC Stan", category: "Music" },
  { mainWord: "Honey Singh", imposterWord: "Badshah", category: "Music" },
  { mainWord: "Karan Aujla", imposterWord: "Shubh", category: "Punjabi Music" },
  { mainWord: "Shubh", imposterWord: "AP Dhillon", category: "Punjabi Music" },
  { mainWord: "Excuses", imposterWord: "Brown Munde", category: "Songs" },
  { mainWord: "Heeriye", imposterWord: "Husn", category: "Songs" },
  { mainWord: "Chaleya", imposterWord: "Satranga", category: "Songs" },
  { mainWord: "Kesariya", imposterWord: "Rasiya", category: "Songs" },
  { mainWord: "Tum Hi Ho", imposterWord: "Agar Tum Saath Ho", category: "Songs" },
  { mainWord: "Apna Bana Le", imposterWord: "Tere Vaaste", category: "Songs" },
  { mainWord: "O Maahi", imposterWord: "Satranga", category: "Songs" },
  { mainWord: "Maan Meri Jaan", imposterWord: "Husn", category: "Songs" },

  // ==================== OTT ====================
  { mainWord: "Mirzapur", imposterWord: "Sacred Games", category: "OTT" },
  { mainWord: "Panchayat", imposterWord: "Gullak", category: "OTT" },
  { mainWord: "Farzi", imposterWord: "The Family Man", category: "OTT" },
  { mainWord: "Kota Factory", imposterWord: "Aspirants", category: "OTT" },
  { mainWord: "Scam 1992", imposterWord: "The Big Bull", category: "OTT" },
  { mainWord: "Mismatched", imposterWord: "College Romance", category: "OTT" },
  { mainWord: "TVF Pitchers", imposterWord: "Shark Tank India", category: "OTT" },
  { mainWord: "Kota Factory", imposterWord: "12th Fail", category: "Student Culture" },
  { mainWord: "Wednesday", imposterWord: "Stranger Things", category: "OTT" },
  { mainWord: "Money Heist", imposterWord: "Squid Game", category: "OTT" },
  { mainWord: "Breaking Bad", imposterWord: "Peaky Blinders", category: "OTT" },
  { mainWord: "Friends", imposterWord: "How I Met Your Mother", category: "OTT" },
  { mainWord: "The Office", imposterWord: "Friends", category: "OTT" },

  // ==================== INDIAN SOCIAL MEDIA ====================
  { mainWord: "Instagram", imposterWord: "Snapchat", category: "Social Media" },
  { mainWord: "Instagram", imposterWord: "TikTok", category: "Social Media" },
  { mainWord: "YouTube", imposterWord: "Instagram", category: "Social Media" },
  { mainWord: "Threads", imposterWord: "Twitter", category: "Social Media" },
  { mainWord: "Reddit", imposterWord: "X", category: "Social Media" },
  { mainWord: "WhatsApp", imposterWord: "Telegram", category: "Messaging" },
  { mainWord: "Snapchat", imposterWord: "Instagram", category: "Social Media" },
  { mainWord: "Reels", imposterWord: "YouTube Shorts", category: "Social Media" },
  { mainWord: "Close Friends", imposterWord: "Private Story", category: "Instagram" },
  { mainWord: "Story", imposterWord: "Reel", category: "Instagram" },
  { mainWord: "DM", imposterWord: "Reply", category: "Social Media" },
  { mainWord: "Seen", imposterWord: "Delivered", category: "Messaging" },
  { mainWord: "Ghosting", imposterWord: "Ignoring", category: "Internet Culture" },
  { mainWord: "Block", imposterWord: "Restrict", category: "Instagram" },
  { mainWord: "Like", imposterWord: "Comment", category: "Social Media" },
  { mainWord: "Meme", imposterWord: "Reaction", category: "Internet Culture" },

  // ==================== GEN Z SLANG ====================
  { mainWord: "Rizz", imposterWord: "Charm", category: "Gen Z" },
  { mainWord: "Delulu", imposterWord: "Manifesting", category: "Gen Z" },
  { mainWord: "Sigma", imposterWord: "Alpha", category: "Gen Z" },
  { mainWord: "Aura", imposterWord: "Rizz", category: "Gen Z" },
  { mainWord: "Brainrot", imposterWord: "Meme", category: "Gen Z" },
  { mainWord: "Sus", imposterWord: "Shady", category: "Gen Z" },
  { mainWord: "Based", imposterWord: "Savage", category: "Gen Z" },
  { mainWord: "Slay", imposterWord: "Ate", category: "Gen Z" },
  { mainWord: "Cringe", imposterWord: "Awkward", category: "Gen Z" },
  { mainWord: "Ghosting", imposterWord: "Breadcrumbing", category: "Dating" },
  { mainWord: "Situationship", imposterWord: "Talking Stage", category: "Dating" },
  { mainWord: "Red Flag", imposterWord: "Green Flag", category: "Dating" },
  { mainWord: "Soft Launch", imposterWord: "Hard Launch", category: "Dating" },
  { mainWord: "Crush", imposterWord: "Situationship", category: "Dating" },

  // ==================== INDIAN APPS ====================
  { mainWord: "PhonePe", imposterWord: "Google Pay", category: "Indian Apps" },
  { mainWord: "Google Pay", imposterWord: "Paytm", category: "Indian Apps" },
  { mainWord: "Zepto", imposterWord: "Blinkit", category: "Indian Apps" },
  { mainWord: "Swiggy", imposterWord: "Zomato", category: "Indian Apps" },
  { mainWord: "Ola", imposterWord: "Uber", category: "Indian Apps" },
  { mainWord: "Jio", imposterWord: "Airtel", category: "Indian Brands" },
  { mainWord: "Amazon", imposterWord: "Flipkart", category: "Shopping" },
  { mainWord: "Myntra", imposterWord: "Ajio", category: "Shopping" },
  { mainWord: "CRED", imposterWord: "Paytm", category: "Finance" },
  { mainWord: "Netflix", imposterWord: "Prime Video", category: "Streaming" },
  { mainWord: "Hotstar", imposterWord: "JioCinema", category: "Streaming" },
  { mainWord: "Spotify", imposterWord: "YouTube Music", category: "Music Apps" },

  // ==================== FOOD ====================
  { mainWord: "Maggi", imposterWord: "Yippee", category: "Food" },
  { mainWord: "Pani Puri", imposterWord: "Bhel Puri", category: "Indian Food" },
  { mainWord: "Samosa", imposterWord: "Kachori", category: "Indian Food" },
  { mainWord: "Vada Pav", imposterWord: "Dabeli", category: "Indian Food" },
  { mainWord: "Biryani", imposterWord: "Pulao", category: "Indian Food" },
  { mainWord: "Momos", imposterWord: "Spring Rolls", category: "Indian Food" },
  { mainWord: "Paneer Tikka", imposterWord: "Chicken Tikka", category: "Indian Food" },
  { mainWord: "Butter Chicken", imposterWord: "Chicken Tikka Masala", category: "Indian Food" },
  { mainWord: "Dosa", imposterWord: "Uttapam", category: "South Indian Food" },
  { mainWord: "Idli", imposterWord: "Dhokla", category: "Indian Food" },
  { mainWord: "Chole Bhature", imposterWord: "Rajma Chawal", category: "Indian Food" },
  { mainWord: "Paratha", imposterWord: "Naan", category: "Indian Food" },
  { mainWord: "Gulab Jamun", imposterWord: "Rasgulla", category: "Desserts" },
  { mainWord: "Jalebi", imposterWord: "Imarti", category: "Desserts" },
  { mainWord: "Kulfi", imposterWord: "Ice Cream", category: "Desserts" },
  { mainWord: "Pav Bhaji", imposterWord: "Vada Pav", category: "Street Food" },
  { mainWord: "Chai", imposterWord: "Coffee", category: "Drinks" },
  { mainWord: "Cold Coffee", imposterWord: "Milkshake", category: "Drinks" },
  { mainWord: "Coke", imposterWord: "Pepsi", category: "Drinks" },
  { mainWord: "Thums Up", imposterWord: "Coca Cola", category: "Drinks" },

  // ==================== CRICKET / IPL ====================
  { mainWord: "Virat Kohli", imposterWord: "Rohit Sharma", category: "Cricket" },
  { mainWord: "MS Dhoni", imposterWord: "Hardik Pandya", category: "Cricket" },
  { mainWord: "Jasprit Bumrah", imposterWord: "Mohammed Shami", category: "Cricket" },
  { mainWord: "Shubman Gill", imposterWord: "Yashasvi Jaiswal", category: "Cricket" },
  { mainWord: "Rishabh Pant", imposterWord: "KL Rahul", category: "Cricket" },
  { mainWord: "RCB", imposterWord: "CSK", category: "IPL" },
  { mainWord: "Mumbai Indians", imposterWord: "Chennai Super Kings", category: "IPL" },
  { mainWord: "KKR", imposterWord: "SRH", category: "IPL" },
  { mainWord: "GT", imposterWord: "LSG", category: "IPL" },
  { mainWord: "IPL", imposterWord: "World Cup", category: "Cricket" },
  { mainWord: "Test Match", imposterWord: "ODI", category: "Cricket" },
  { mainWord: "T20", imposterWord: "ODI", category: "Cricket" },
  { mainWord: "Six", imposterWord: "Four", category: "Cricket" },
  { mainWord: "Yorker", imposterWord: "Bouncer", category: "Cricket" },
  { mainWord: "Wicket", imposterWord: "Run Out", category: "Cricket" },

  // ==================== COLLEGE / STUDENT LIFE ====================
  { mainWord: "JEE", imposterWord: "NEET", category: "Exams" },
  { mainWord: "JEE Main", imposterWord: "JEE Advanced", category: "Exams" },
  { mainWord: "IIT", imposterWord: "NIT", category: "Colleges" },
  { mainWord: "IIT", imposterWord: "IIM", category: "Colleges" },
  { mainWord: "UPSC", imposterWord: "JEE", category: "Exams" },
  { mainWord: "Dropper", imposterWord: "Repeater", category: "Student Life" },
  { mainWord: "Coaching", imposterWord: "Online Course", category: "Student Life" },
  { mainWord: "Hostel", imposterWord: "PG", category: "Student Life" },
  { mainWord: "Attendance", imposterWord: "Assignment", category: "College Life" },
  { mainWord: "Proxy", imposterWord: "Biometric", category: "College Life" },
  { mainWord: "Backlog", imposterWord: "Supplementary", category: "College Life" },
  { mainWord: "Freshers", imposterWord: "Farewell", category: "College Life" },
  { mainWord: "Professor", imposterWord: "Teacher", category: "College Life" },
  { mainWord: "Canteen", imposterWord: "Mess", category: "College Life" },
  { mainWord: "Assignment", imposterWord: "Project", category: "College Life" },
  { mainWord: "Exam", imposterWord: "Quiz", category: "College Life" },

  // ==================== FESTIVALS ====================
  { mainWord: "Diwali", imposterWord: "Holi", category: "Festivals" },
  { mainWord: "Ganpati", imposterWord: "Navratri", category: "Festivals" },
  { mainWord: "Garba", imposterWord: "Dandiya", category: "Festivals" },
  { mainWord: "Makar Sankranti", imposterWord: "Lohri", category: "Festivals" },
  { mainWord: "Eid", imposterWord: "Bakrid", category: "Festivals" },
  { mainWord: "Christmas", imposterWord: "New Year", category: "Festivals" },
  { mainWord: "Raksha Bandhan", imposterWord: "Bhai Dooj", category: "Festivals" },
  { mainWord: "Dussehra", imposterWord: "Diwali", category: "Festivals" },
  { mainWord: "Navratri", imposterWord: "Durga Puja", category: "Festivals" },

  // ==================== CONTROVERSY / INTERNET ====================
  { mainWord: "Cancel Culture", imposterWord: "Boycott", category: "Internet Culture" },
  { mainWord: "Controversy", imposterWord: "Scandal", category: "Internet Culture" },
  { mainWord: "Roast", imposterWord: "Criticism", category: "Internet Culture" },
  { mainWord: "Troll", imposterWord: "Hater", category: "Internet Culture" },
  { mainWord: "Viral", imposterWord: "Trending", category: "Internet Culture" },
  { mainWord: "Meme", imposterWord: "Shitpost", category: "Internet Culture" },
  { mainWord: "Leak", imposterWord: "Rumour", category: "Internet Culture" },
  { mainWord: "Expose", imposterWord: "Callout", category: "Internet Culture" },
  { mainWord: "Clickbait", imposterWord: "Ragebait", category: "Internet Culture" },
  { mainWord: "FOMO", imposterWord: "YOLO", category: "Gen Z" },
  { mainWord: "Viral Reel", imposterWord: "Meme", category: "Internet Culture" },
  { mainWord: "Influencer", imposterWord: "Content Creator", category: "Internet Culture" },
  { mainWord: "Fan Account", imposterWord: "Stan Account", category: "Internet Culture" },
  { mainWord: "Fan War", imposterWord: "Twitter War", category: "Internet Culture" },

  // ==================== DATING ====================
  { mainWord: "Crush", imposterWord: "Situationship", category: "Dating" },
  { mainWord: "Situationship", imposterWord: "Talking Stage", category: "Dating" },
  { mainWord: "Ghosting", imposterWord: "Breadcrumbing", category: "Dating" },
  { mainWord: "Red Flag", imposterWord: "Green Flag", category: "Dating" },
  { mainWord: "Soft Launch", imposterWord: "Hard Launch", category: "Dating" },
  { mainWord: "Breakup", imposterWord: "Rejection", category: "Dating" },
  { mainWord: "Date", imposterWord: "Hangout", category: "Dating" },
  { mainWord: "Tinder", imposterWord: "Bumble", category: "Dating Apps" },
  { mainWord: "Dating App", imposterWord: "Instagram", category: "Dating" },
  { mainWord: "Best Friend", imposterWord: "Crush", category: "Relationships" },

  // ==================== TRAVEL / INDIA ====================
  { mainWord: "Goa", imposterWord: "Manali", category: "Travel" },
  { mainWord: "Mumbai", imposterWord: "Delhi", category: "India" },
  { mainWord: "Bangalore", imposterWord: "Hyderabad", category: "India" },
  { mainWord: "Pune", imposterWord: "Mumbai", category: "India" },
  { mainWord: "Delhi Metro", imposterWord: "Mumbai Local", category: "Transportation" },
  { mainWord: "Auto", imposterWord: "Cab", category: "Transportation" },
  { mainWord: "Ola", imposterWord: "Uber", category: "Transportation" },
  { mainWord: "Metro", imposterWord: "Local Train", category: "Transportation" },
  { mainWord: "Flight", imposterWord: "Train", category: "Transportation" },
  { mainWord: "Hotel", imposterWord: "Hostel", category: "Travel" },
  { mainWord: "Beach", imposterWord: "Pool", category: "Travel" },
  { mainWord: "Hill Station", imposterWord: "Beach Resort", category: "Travel" },

  // ==================== TECHNOLOGY ====================
  { mainWord: "iPhone", imposterWord: "Samsung", category: "Technology" },
  { mainWord: "Android", imposterWord: "iOS", category: "Technology" },
  { mainWord: "MacBook", imposterWord: "Windows Laptop", category: "Technology" },
  { mainWord: "AirPods", imposterWord: "Galaxy Buds", category: "Technology" },
  { mainWord: "ChatGPT", imposterWord: "Gemini", category: "AI" },
  { mainWord: "Claude", imposterWord: "ChatGPT", category: "AI" },
  { mainWord: "Google", imposterWord: "Bing", category: "Technology" },
  { mainWord: "Chrome", imposterWord: "Edge", category: "Technology" },
  { mainWord: "WhatsApp", imposterWord: "Telegram", category: "Messaging" },
  { mainWord: "Wi-Fi", imposterWord: "Mobile Data", category: "Technology" },
  { mainWord: "Bluetooth", imposterWord: "Wi-Fi", category: "Technology" },
  { mainWord: "Laptop", imposterWord: "Tablet", category: "Technology" },
  { mainWord: "Power Bank", imposterWord: "Charger", category: "Technology" },

  // ==================== BRANDS ====================
  { mainWord: "Nike", imposterWord: "Adidas", category: "Brands" },
  { mainWord: "Puma", imposterWord: "Reebok", category: "Brands" },
  { mainWord: "Levi's", imposterWord: "Wrangler", category: "Fashion" },
  { mainWord: "Zara", imposterWord: "H&M", category: "Fashion" },
  { mainWord: "Ray-Ban", imposterWord: "Oakley", category: "Fashion" },
  { mainWord: "Rolex", imposterWord: "Casio", category: "Watches" },
  { mainWord: "Red Bull", imposterWord: "Monster", category: "Drinks" },
  { mainWord: "Coca Cola", imposterWord: "Pepsi", category: "Drinks" },
  { mainWord: "Thums Up", imposterWord: "Pepsi", category: "Drinks" },
  { mainWord: "Amul", imposterWord: "Mother Dairy", category: "Indian Brands" },

  // ==================== MEMES ====================
  { mainWord: "Nirmala Sitharaman Meme", imposterWord: "PM Modi Meme", category: "Memes" },
  { mainWord: "Kalesh", imposterWord: "Beef", category: "Memes" },
  { mainWord: "Sigma Edit", imposterWord: "Phonk Edit", category: "Memes" },
  { mainWord: "Indian Dad", imposterWord: "Indian Mom", category: "Memes" },
  { mainWord: "POV", imposterWord: "Storytime", category: "Internet" },
  { mainWord: "NPC", imposterWord: "Bot", category: "Internet" },
  { mainWord: "Brainrot", imposterWord: "Shitpost", category: "Internet" },
  { mainWord: "Dank Meme", imposterWord: "Wholesome Meme", category: "Internet" },
  { mainWord: "Reaction Meme", imposterWord: "GIF", category: "Internet" },
  { mainWord: "Viral Sound", imposterWord: "Trending Song", category: "Internet" },

  // ==================== EVERYDAY GEN Z ====================
  { mainWord: "Night Out", imposterWord: "House Party", category: "Gen Z Life" },
  { mainWord: "Sleepover", imposterWord: "House Party", category: "Gen Z Life" },
  { mainWord: "Gym", imposterWord: "Sports Club", category: "Fitness" },
  { mainWord: "Creatine", imposterWord: "Protein Powder", category: "Fitness" },
  { mainWord: "Pre-Workout", imposterWord: "Energy Drink", category: "Fitness" },
  { mainWord: "Cutting", imposterWord: "Bulking", category: "Fitness" },
  { mainWord: "Gym Bro", imposterWord: "Fitness Influencer", category: "Fitness" },
  { mainWord: "Oversized T-Shirt", imposterWord: "Hoodie", category: "Fashion" },
  { mainWord: "Sneakers", imposterWord: "Running Shoes", category: "Fashion" },
  { mainWord: "Thrift Store", imposterWord: "Streetwear Store", category: "Fashion" },

  // ==================== GAMING ====================
  { mainWord: "BGMI", imposterWord: "Free Fire", category: "Gaming" },
  { mainWord: "Valorant", imposterWord: "CS2", category: "Gaming" },
  { mainWord: "Minecraft", imposterWord: "Roblox", category: "Gaming" },
  { mainWord: "GTA V", imposterWord: "GTA Online", category: "Gaming" },
  { mainWord: "PUBG", imposterWord: "BGMI", category: "Gaming" },
  { mainWord: "PlayStation", imposterWord: "Xbox", category: "Gaming" },
  { mainWord: "PS5", imposterWord: "Gaming PC", category: "Gaming" },
  { mainWord: "Fortnite", imposterWord: "Apex Legends", category: "Gaming" },
  { mainWord: "Among Us", imposterWord: "Goose Goose Duck", category: "Gaming" },

  // ==================== SCHOOL / COLLEGE ====================
  { mainWord: "Backbencher", imposterWord: "Topper", category: "School" },
  { mainWord: "Teacher", imposterWord: "Professor", category: "Education" },
  { mainWord: "Homework", imposterWord: "Assignment", category: "Education" },
  { mainWord: "Exam", imposterWord: "Test", category: "Education" },
  { mainWord: "Principal", imposterWord: "Vice Principal", category: "School" },
  { mainWord: "Canteen", imposterWord: "Cafeteria", category: "School" },
  { mainWord: "Uniform", imposterWord: "Formal Dress", category: "School" },
  { mainWord: "School Trip", imposterWord: "College Trip", category: "Student Life" },
  { mainWord: "Proxy", imposterWord: "Attendance", category: "College" },
  { mainWord: "Last Bench", imposterWord: "Corner Seat", category: "College" },

  // ==================== POP CULTURE ====================
  { mainWord: "Marvel", imposterWord: "DC", category: "Pop Culture" },
  { mainWord: "Iron Man", imposterWord: "Batman", category: "Superheroes" },
  { mainWord: "Spider-Man", imposterWord: "Deadpool", category: "Superheroes" },
  { mainWord: "Thor", imposterWord: "Hulk", category: "Superheroes" },
  { mainWord: "Avengers", imposterWord: "Justice League", category: "Superheroes" },
  { mainWord: "Harry Potter", imposterWord: "Percy Jackson", category: "Pop Culture" },
  { mainWord: "Wednesday", imposterWord: "Wandavision", category: "Pop Culture" },
  { mainWord: "Barbie", imposterWord: "Mean Girls", category: "Pop Culture" },
  { mainWord: "Taylor Swift", imposterWord: "Ariana Grande", category: "Pop Culture" },
  { mainWord: "Justin Bieber", imposterWord: "Shawn Mendes", category: "Pop Culture" }
]

const list2 = [
  { mainWord: "Shah Rukh Khan", imposterWord: "Salman Khan", category: "Bollywood" },
  { mainWord: "Ranbir Kapoor", imposterWord: "Ranveer Singh", category: "Bollywood" },
  { mainWord: "Alia Bhatt", imposterWord: "Deepika Padukone", category: "Bollywood" },
  { mainWord: "Varun Dhawan", imposterWord: "Sidharth Malhotra", category: "Bollywood" },
  { mainWord: "Kartik Aaryan", imposterWord: "Vicky Kaushal", category: "Bollywood" },
  { mainWord: "Rajkummar Rao", imposterWord: "Ayushmann Khurrana", category: "Bollywood" },
  { mainWord: "Dunki", imposterWord: "Jawan", category: "Bollywood Movies" },
  { mainWord: "3 Idiots", imposterWord: "Chhichhore", category: "Bollywood Movies" },
  { mainWord: "Zindagi Na Milegi Dobara", imposterWord: "Dil Chahta Hai", category: "Bollywood Movies" },
  { mainWord: "Yeh Jawaani Hai Deewani", imposterWord: "Wake Up Sid", category: "Bollywood Movies" },

  { mainWord: "Arijit Singh", imposterWord: "Atif Aslam", category: "Music" },
  { mainWord: "AP Dhillon", imposterWord: "Karan Aujla", category: "Music" },
  { mainWord: "Diljit Dosanjh", imposterWord: "Badshah", category: "Music" },
  { mainWord: "Shreya Ghoshal", imposterWord: "Sunidhi Chauhan", category: "Music" },
  { mainWord: "Anuv Jain", imposterWord: "Prateek Kuhad", category: "Music" },
  { mainWord: "Spotify", imposterWord: "YouTube Music", category: "Music" },
  { mainWord: "Spotify Wrapped", imposterWord: "Instagram Recap", category: "Internet Culture" },
  { mainWord: "Concert", imposterWord: "Music Festival", category: "Music" },

  { mainWord: "Bigg Boss", imposterWord: "Splitsvilla", category: "Reality TV" },
  { mainWord: "Koffee With Karan", imposterWord: "The Kapil Sharma Show", category: "Indian TV" },
  { mainWord: "Shark Tank India", imposterWord: "Bigg Boss", category: "Indian TV" },
  { mainWord: "Panchayat", imposterWord: "Gullak", category: "OTT" },
  { mainWord: "Mirzapur", imposterWord: "Sacred Games", category: "OTT" },
  { mainWord: "The Family Man", imposterWord: "Farzi", category: "OTT" },

  { mainWord: "Instagram", imposterWord: "Snapchat", category: "Social Media" },
  { mainWord: "Instagram Reels", imposterWord: "YouTube Shorts", category: "Social Media" },
  { mainWord: "Influencer", imposterWord: "Content Creator", category: "Internet Culture" },
  { mainWord: "Finsta", imposterWord: "Close Friends", category: "Instagram" },
  { mainWord: "Viral Reel", imposterWord: "Meme", category: "Internet Culture" },
  { mainWord: "Reddit", imposterWord: "X", category: "Social Media" },
  { mainWord: "Twitter", imposterWord: "Threads", category: "Social Media" },
  { mainWord: "LinkedIn", imposterWord: "Instagram", category: "Social Media" },

  { mainWord: "UPI", imposterWord: "Credit Card", category: "India" },
  { mainWord: "PhonePe", imposterWord: "Google Pay", category: "India" },
  { mainWord: "Zepto", imposterWord: "Blinkit", category: "India" },
  { mainWord: "Swiggy", imposterWord: "Zomato", category: "India" },
  { mainWord: "Ola", imposterWord: "Uber", category: "India" },
  { mainWord: "Jio", imposterWord: "Airtel", category: "India" },
  { mainWord: "IRCTC", imposterWord: "RedBus", category: "India" },
  { mainWord: "Amazon", imposterWord: "Flipkart", category: "India" },

  { mainWord: "Chai", imposterWord: "Coffee", category: "Indian Life" },
  { mainWord: "Maggi", imposterWord: "Yippee", category: "Food" },
  { mainWord: "Pani Puri", imposterWord: "Bhel Puri", category: "Indian Food" },
  { mainWord: "Samosa", imposterWord: "Kachori", category: "Indian Food" },
  { mainWord: "Vada Pav", imposterWord: "Dabeli", category: "Indian Food" },
  { mainWord: "Biryani", imposterWord: "Pulao", category: "Indian Food" },
  { mainWord: "Momos", imposterWord: "Spring Rolls", category: "Indian Food" },
  { mainWord: "Paneer Tikka", imposterWord: "Chicken Tikka", category: "Indian Food" },

  { mainWord: "IIT", imposterWord: "IIM", category: "College" },
  { mainWord: "JEE", imposterWord: "NEET", category: "Exams" },
  { mainWord: "JEE Main", imposterWord: "JEE Advanced", category: "Exams" },
  { mainWord: "Hostel", imposterWord: "PG", category: "College Life" },
  { mainWord: "Attendance", imposterWord: "Assignment", category: "College Life" },
  { mainWord: "Proxy", imposterWord: "Biometric", category: "College Life" },
  { mainWord: "Backlog", imposterWord: "Supplementary Exam", category: "College Life" },
  { mainWord: "Freshers", imposterWord: "Farewell", category: "College Life" },

  { mainWord: "Virat Kohli", imposterWord: "Rohit Sharma", category: "Cricket" },
  { mainWord: "MS Dhoni", imposterWord: "Hardik Pandya", category: "Cricket" },
  { mainWord: "RCB", imposterWord: "CSK", category: "IPL" },
  { mainWord: "Mumbai Indians", imposterWord: "Chennai Super Kings", category: "IPL" },
  { mainWord: "IPL", imposterWord: "World Cup", category: "Cricket" },
  { mainWord: "Cricket", imposterWord: "Football", category: "Sports" },

  { mainWord: "UPSC", imposterWord: "JEE", category: "Exams" },
  { mainWord: "NEET Aspirant", imposterWord: "JEE Aspirant", category: "Student Life" },
  { mainWord: "Dropper", imposterWord: "Repeater", category: "Student Life" },
  { mainWord: "Coaching", imposterWord: "Online Course", category: "Student Life" },
  { mainWord: "Doubt", imposterWord: "Backlog", category: "Student Life" },

  { mainWord: "Diwali", imposterWord: "Holi", category: "Festivals" },
  { mainWord: "Garba", imposterWord: "Dandiya", category: "Festivals" },
  { mainWord: "Ganpati", imposterWord: "Navratri", category: "Festivals" },
  { mainWord: "Lohri", imposterWord: "Makar Sankranti", category: "Festivals" },

  { mainWord: "Crush", imposterWord: "Situationship", category: "Dating" },
  { mainWord: "Ghosting", imposterWord: "Ignoring", category: "Dating" },
  { mainWord: "Breakup", imposterWord: "Rejection", category: "Dating" },
  { mainWord: "Talking Stage", imposterWord: "Relationship", category: "Dating" },
  { mainWord: "Red Flag", imposterWord: "Green Flag", category: "Dating" },
  { mainWord: "Best Friend", imposterWord: "Crush", category: "Relationships" },

  { mainWord: "Gen Z", imposterWord: "Millennial", category: "Generations" },
  { mainWord: "Brainrot", imposterWord: "Meme", category: "Internet Culture" },
  { mainWord: "Sigma", imposterWord: "Alpha", category: "Internet Culture" },
  { mainWord: "Rizz", imposterWord: "Charm", category: "Internet Culture" },
  { mainWord: "Delulu", imposterWord: "Manifesting", category: "Internet Culture" },
  { mainWord: "Cancel Culture", imposterWord: "Boycott", category: "Internet Culture" },
  { mainWord: "Controversy", imposterWord: "Scandal", category: "Internet Culture" },

  { mainWord: "Papparazzi", imposterWord: "Fan Page", category: "Celebrity" },
  { mainWord: "Bollywood Nepotism", imposterWord: "Star Kid", category: "Bollywood" },
  { mainWord: "Celebrity Roast", imposterWord: "Comedy Roast", category: "Entertainment" },
  { mainWord: "Award Show", imposterWord: "Film Festival", category: "Entertainment" },

  { mainWord: "Monsoon", imposterWord: "Winter", category: "India" },
  { mainWord: "Delhi", imposterWord: "Mumbai", category: "India" },
  { mainWord: "Goa", imposterWord: "Manali", category: "Travel" },
  { mainWord: "Metro", imposterWord: "Local Train", category: "India" },
  { mainWord: "Auto Rickshaw", imposterWord: "E-Rickshaw", category: "India" }
]

const list3 = [
  { mainWord: "Pancake", imposterWord: "Waffle", category: "Food" },
  { mainWord: "Burger", imposterWord: "Sandwich", category: "Food" },
  { mainWord: "Cupcake", imposterWord: "Muffin", category: "Food" },
  { mainWord: "Pizza", imposterWord: "Flatbread", category: "Food" },
  { mainWord: "Popcorn", imposterWord: "Chips", category: "Food" },
  { mainWord: "Ice Cream", imposterWord: "Frozen Yogurt", category: "Food" },
  { mainWord: "Noodles", imposterWord: "Spaghetti", category: "Food" },
  { mainWord: "Donut", imposterWord: "Bagel", category: "Food" },

  { mainWord: "Laptop", imposterWord: "Tablet", category: "Technology" },
  { mainWord: "Smartphone", imposterWord: "Remote Control", category: "Technology" },
  { mainWord: "Keyboard", imposterWord: "Piano", category: "Technology" },
  { mainWord: "Headphones", imposterWord: "Earbuds", category: "Technology" },
  { mainWord: "Charger", imposterWord: "Power Bank", category: "Technology" },
  { mainWord: "Wi-Fi", imposterWord: "Bluetooth", category: "Technology" },
  { mainWord: "Camera", imposterWord: "Webcam", category: "Technology" },
  { mainWord: "Smartwatch", imposterWord: "Fitness Band", category: "Technology" },

  { mainWord: "Hotel", imposterWord: "Motel", category: "Places" },
  { mainWord: "Airport", imposterWord: "Train Station", category: "Places" },
  { mainWord: "Library", imposterWord: "Bookstore", category: "Places" },
  { mainWord: "Cinema", imposterWord: "Theater", category: "Places" },
  { mainWord: "Supermarket", imposterWord: "Convenience Store", category: "Places" },
  { mainWord: "Beach", imposterWord: "Swimming Pool", category: "Places" },
  { mainWord: "School", imposterWord: "College", category: "Places" },
  { mainWord: "Restaurant", imposterWord: "Cafe", category: "Places" },

  { mainWord: "Bicycle", imposterWord: "Motorcycle", category: "Transportation" },
  { mainWord: "Bus", imposterWord: "Train", category: "Transportation" },
  { mainWord: "Taxi", imposterWord: "Uber", category: "Transportation" },
  { mainWord: "Airplane", imposterWord: "Helicopter", category: "Transportation" },
  { mainWord: "Scooter", imposterWord: "Skateboard", category: "Transportation" },
  { mainWord: "Subway", imposterWord: "Tram", category: "Transportation" },
  { mainWord: "Boat", imposterWord: "Yacht", category: "Transportation" },
  { mainWord: "Car", imposterWord: "Van", category: "Transportation" },

  { mainWord: "Pillow", imposterWord: "Cushion", category: "Household Items" },
  { mainWord: "Curtain", imposterWord: "Blind", category: "Household Items" },
  { mainWord: "Sofa", imposterWord: "Armchair", category: "Household Items" },
  { mainWord: "Broom", imposterWord: "Mop", category: "Household Items" },
  { mainWord: "Refrigerator", imposterWord: "Freezer", category: "Household Items" },
  { mainWord: "Mirror", imposterWord: "Window", category: "Household Items" },

  { mainWord: "Dolphin", imposterWord: "Whale", category: "Animals" },
  { mainWord: "Rabbit", imposterWord: "Hare", category: "Animals" },
  { mainWord: "Frog", imposterWord: "Toad", category: "Animals" },
  { mainWord: "Butterfly", imposterWord: "Moth", category: "Animals" },

  { mainWord: "Thunder", imposterWord: "Lightning", category: "Nature" },
  { mainWord: "Volcano", imposterWord: "Mountain", category: "Nature" }
]

const custom = [
  { mainWord: "Nightmare", imposterWord: "Dreamer", category: "Friends" },
  { mainWord: "Zenitsu", imposterWord: "Giyu", category: "Friends" },
  { mainWord: "Tulip", imposterWord: "Lily", category: "Friends" },
  { mainWord: "Yeh Kaali Kaali Ankhein", imposterWord: "Tururu", category: "Friends" }
]

const all = [...list1, ...list2, ...list3, ...custom]

const unique = []
const seen = new Set()

for (const pair of all) {
  const key = pair.mainWord.toLowerCase() + '|' + pair.imposterWord.toLowerCase()
  if (!seen.has(key)) {
    seen.add(key)
    unique.push(pair)
  }
}

const jsContent = 'export const WORD_PAIRS = ' + JSON.stringify(unique, null, 2) + ';'
fs.writeFileSync('G:/React/Games/SusWord/server/src/wordPairs.js', jsContent)

console.log('Done! Unique pairs:', unique.length)
